// Typelizer digest 441638e4527b7b7e044c09f70f5247d5
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Invoice} from '$types/typelizer'

type Customer = {
  id: number;
  name: string | null;
  notes: string | null;
  address: string | null;
  contact: string | null;
  updated_at: string;
  invoices: Array<Invoice>;
}

export type { Customer };
