// Typelizer digest ee01b36d3e3a5021fc6fd9681436f7e8
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Invoice} from '$types/typelizer'

type Customer = {
  id: number;
  name: string | null;
  notes: string | null;
  address: string | null;
  contact: string | null;
  updated_at: string;
  invoices: Array<Invoice>;
  today_invoices: Array<Invoice>;
}

export type { Customer };
