// Typelizer digest 73618c7d11786579a3e23f8545aa3419
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Customer, Item} from '$types/typelizer'

type Invoice = {
  id: number;
  date: string | null;
  code: string | null;
  address: string;
  customer: Customer;
  items: Array<Item>;
}

export type { Invoice };
