// Typelizer digest 97317a51380e81e8de6adbf0d404ca19
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Customer, Item} from '$types/typelizer'

type Invoice = {
  id: number;
  date: string | null;
  code: string | null;
  address: string | null;
  customer: Customer;
  items: Array<Item>;
}

export type { Invoice };
