// Typelizer digest 8fa767a5bdf34b40762ad0b7c63cc582
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Item = {
  id: number;
  name: string;
  notes: string | null;
  cost_price: number;
  selling_price: number;
  stock: string | null;
  code: string | null;
  category: string | null;
  tag: string;
  quantity: number;
  quantity_unit: string;
  updated_at: string;
  source: Item;
}

export type { Item };
