// Typelizer digest ad867e70cb53f6650972d7fb20edba2c
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Item = {
  id: number;
  name: string | null;
  notes: string | null;
  cost_price: number;
  selling_price: number;
  stock: string | null;
  code: string | null;
  category: string | null;
  tag: string;
  quantity: number;
  quantity_unit: string;
  updated_at: string;
}

export type { Item };
