// Typelizer digest 1927519d355da7e180ab11e03396f37d
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Item = {
  id: number;
  name: string;
  notes: string | null;
  cost_price: number;
  selling_price: number;
  stock: string | null;
  code: string | null;
  category: string | null;
  tag: string;
  quantity: number;
  quantity_unit: string;
  updated_at: string;
}

export type { Item };
